# Site settings
title: OPEN | Exemplary Workforce Training Programs
email: https://github.com/billymeinke/cc-toolkits
description: "Profiles of exemplary workforce training programs supported by the U.S. Department of Labor TAACCCT program."
github_username:  billymeinke
baseurl: "/taaccct"

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
gems: ['jekyll-less','kramdown']
